version: '3.9'

services:
  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.11
    container_name: selenoid-ui
    ports:
      - "8080:8080"
    environment:
      TZ: "America/Sao_Paulo"
    dns:
      - 8.8.8.8
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      --selenoid-uri http://selenoid:4444 --allowed-origin *
    networks:
      - selenoid

  selenoid:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - "./browsers/browsers.json:/etc/selenoid/browsers.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      TZ: "America/Sao_Paulo"
    dns:
      - 8.8.8.8
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      -conf /etc/selenoid/browsers.json 
      -container-network selenoid 
      -limit 10
    networks:
      - selenoid

networks:
  selenoid:
    external: true
